version: '3.9'
services:
  db:
    image: postgres:15.1
    ports:
      - '5432:5432'
    volumes:
      - nextjs-prisma-graphql-sample-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nextjs-prisma-graphql-sample

  mailhog:
    image: mailhog/mailhog
    ports:
      - '8025:8025'
      - '1025:1025'

volumes:
  nextjs-prisma-graphql-sample-postgres:
